CREATE TABLE tokens (
    id BINARY(16) PRIMARY KEY,
    name TINYTEXT NOT NULL,
    email TINYTEXT NOT NULL,
    token TINYTEXT NOT NULL,
    user_id TINYTEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01'
);
