CREATE TABLE artifacts (
    id BINARY(16) NOT NULL,
    name TINYTEXT NOT NULL,
    content MEDIUMBLOB NOT NULL,
    metric_id BINARY(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
    PRIMARY KEY (id)
);
