CREATE TABLE participants (
  id BINARY(16) NOT NULL,
  deployment_id BINARY(16) NOT NULL,
  user_id TEXT NOT NULL,
  selector TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01',
  PRIMARY KEY (id),
  FOREIGN KEY (deployment_id) REFERENCES deployments(id)
);